name: Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and publish new image
        run: |
          docker login --username $docker_username --password $docker_password
          docker build . -t horodchukanton/ahaproject:edge
          docker push horodchukanton/ahaproject:edge
        env:
          docker_username: horodchukanton
          docker_password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}