name: 'Run perl tests (prove)'

on: ['push']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        perl: [ '5.30' ]
    #        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    #        perl: [ '5.30', '5.28' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      # Install perl
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      # Show installed
      - run: perl -V
      # Install project dependencies
      - run: cpanm --installdeps --notest .
      # Run perl tests
      - run: prove -lv t